version: "3"
services:
  backend:
    build: ./server
    ports:
      - "5050:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./client/.env
